### ISSUE TITLE
Intentionally prevent my VM to be started with "prepare/begin/start.sh" hook. How?

### ISSUE THREAD

**Issue by rizzini** [PassthroughPOST/VFIO-Tools#11]
Is there any way/command to my `/etc/libvirt/hooks/qemu.d/win10/prepare/begin/start.sh` intentionally prevent my VM to be started? I'm setting up some conditions tests before the VM can be started.

**Comment by SharkWipf** [comment]
If your hook script exits with a non-zero exit code (`exit 1`), I believe it _should_ halt the startup and throw an error on the starting process.  
There were some bugs with this in the hook helper script a while ago where it didn't always pass the error code to the parent process, I believe they should have been fixed, if not, let me know.

**Comment by rizzini** [comment]
I put GPU passthrough on hold for awhile. When I get back to it, I'll definitely try that and get back to you here.
